calculator:
  workingDaysInMonth: 22
  countryRates:
    - countryCode: PL
      countryName: Poland
      currencyCode: PLN
      incomeTaxPercentage: 19
      fixedCost: 1200
    - countryCode: UK
      countryName: England
      currencyCode: GBP
      incomeTaxPercentage: 25
      fixedCost: 600
    - countryCode: DE
      countryName: Germany
      currencyCode: EUR
      incomeTaxPercentage: 20
      fixedCost: 800
